class Button:
    START = 'Старт'
    HELP = 'Помощь'
    REPORTS = 'Отчеты'
    SET_COMMANDS = 'Установить команды'
    PEOPLE_IN_ZONE = 'Люди в зоне'
    TOTAL_REPORT = 'Итоговый отчет'
    SUM_REPORT = 'Суммовой отчет'
    TODAY = 'За сегодня'
    YESTERDAY = 'За вчера'
    OTHER_PERIOD = 'Произвольный период'
    SET = 'Установить'
    REQUEST = 'Выполнить запрос'
    CANCEL = 'Отменить'
    PRINT = 'Напечатать на экране'
    SAVE = 'Сохранить'
    CHANGE_PERIOD = 'Изменить период'
    HOME = 'На главную'
