version: '3.8'

services:

  barsic-bot:
    container_name: barsic-bot
    hostname: barsic-bot
    build: .
    environment:
      DEBUG: ${DEBUG}
      PROJECT_NAME: ${PROJECT_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # AppSettings
      BOT_TELEGRAM_TOKEN: ${BOT_TELEGRAM_TOKEN}
      USER_PASSWORD: ${USER_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      BARSIC_WEB_HOST: ${BARSIC_WEB_HOST}
      BARSIC_WEB_PORT: ${BARSIC_WEB_PORT}
      WRITE_PASSWORD_LIMIT_PER_DAY: ${WRITE_PASSWORD_LIMIT_PER_DAY}
    volumes:
      - ./:/opt/app/
    networks:
      network:
    depends_on:
      - redis

  redis:
    container_name: redis
    hostname: redis
    image: redis:7.2-rc1
    environment:
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD}
    volumes:
      - redis:/data
    expose:
      - "6379"
    networks:
      - network

volumes:
  redis:

networks:
  network: